### ISSUE TITLE
image duplicate

### ISSUE THREAD

**Issue by brokeniceinteractive** [zhangao0086/DKImagePickerController#115] opened 2016-04-26 09:33 UTC
if i select a cutted image i obtain a photo twice from this method: 

`fetchOriginalImageWithCompleteBlock({ (image) -> Void in`

**Comment by zhangao0086** [comment] 2016-05-02 14:52
it sounds a bit strange :( I cannot reproduce it :(

**Comment by zhangao0086** [comment] 2016-05-22 16:29
ping...

**Comment by brokeniceinteractive** [comment] 2016-05-22 17:43
I have do this take a Photo forma camera, edit it with iOS image and cut and resize it! Then when i select this from the app i obtain twice!

**Comment by zhangao0086** [comment] 2016-05-23 08:18
I think the problem is fixed now :)

**Comment by brokeniceinteractive** [comment] 2016-05-24 09:47
i updated to last version 3.2.1 but the problem is the same!

**Comment by brokeniceinteractive** [comment] 2016-05-25 07:36
Sorry!!!!!! the problem has been solved! thanks!  another question, before the update i used this:

`imagesel.fetchAVAssetWithCompleteBlock({ (avAsset) -> Void in
avAsset.URL
})`

but now does not work, how can i get URL?

**Comment by brokeniceinteractive** [comment] 2016-05-25 08:05
i solved in this way, is the right way?

let urlAsset = avAsset.AVAsset as! AVURLAsset
let url = urlAsset.URL

**Comment by zhangao0086** [comment] 2016-05-25 08:20
This way works on normal video, for slow motion video, avAsset is an `AVComposition` not `AVURLAsset`.
You can try the `PHImageFileSandboxExtensionTokenKey` of the `info`:
![3de95ac4-dacb-4cb1-b558-755f7755ba96](https://cloud.githubusercontent.com/assets/7742344/15532846/57304c24-2294-11e6-890a-7ce644b2e340.png)

**Comment by brokeniceinteractive** [comment] 2016-05-25 08:33
will be nice something like this:

`fune isNormalVideo(asset:AVAsset){
if let _ = asset as? [AVURLAsset] {
    return true
}
return false
}`

and

`fune isSlowMotionVideo(asset:AVAsset){
if let _ = asset as? [AVComposition] {
    return true
}
return false
}`

What do you think?

**Comment by zhangao0086** [comment] 2016-05-25 09:14
It's no problem :)

**Comment by brokeniceinteractive** [comment] 2016-05-25 09:25
This are correct:

`func isNormalVideo(asset:AVAsset) -> Bool{
        if let _ = asset as? AVURLAsset {
            return true
        }
        return false
    }
    func isSlowMotionVideo(asset:AVAsset) -> Bool{
        if let _ = asset as? AVComposition {
            return true
        }
        return false
    }`

**Comment by zhangao0086** [comment] 2016-05-25 09:30
Maybe I should go see an opthamologist 😅😅😅

**Comment by brokeniceinteractive** [comment] 2016-05-25 09:33
👍 no problem!

**Comment by zhangao0086** [comment] 2016-08-07 15:58
Close this thread.

**Closed by zhangao0086** 2016-08-07 15:58 UTC
