### ISSUE TITLE
swift 5 

### ISSUE THREAD

**Issue by Ranaios** [zhangao0086/DKImagePickerController#607] opened 2019-07-01 11:19 UTC
how can i use it for swift 5 
there are a lot of undeclared type things

**Comment by zhangao0086** [comment] 2019-07-02 16:13
Hi @Ranaios 

I made a small project trying to reproduce it but failed. Could you check it?
[TestDKImagePickerControllerSwift.zip](https://github.com/zhangao0086/DKImagePickerController/files/3350944/TestDKImagePickerControllerSwift.zip)

**Comment by Ranaios** [comment] 2019-07-03 12:26
test demo worked with me but didn't show me the cropping view, i tried but failed

**Comment by yu-t** [comment] 2019-07-17 12:16
Hi, for me it doesn't work. I'm getting 
<img width="430" alt="Снимок экрана 2019-07-17 в 15 14 51" src="https://user-images.githubusercontent.com/2045461/61374769-dfd72580-a8a5-11e9-99ca-0f41e40d53d3.png">

**Comment by galip91** [comment] 2019-07-31 13:11
Can you perhaps release a Swift 5 version to cocoapods, so we don't have to convert it manually every time we update our pods?

**Comment by zhangao0086** [comment] 2019-07-31 14:26
Hi @galip91 Latest Version(`4.1.5`) already is Swift 5

**Comment by galip91** [comment] 2019-08-05 09:30
Hi. You're right 4.1.5 is Swift 5 and I already have 4.1.5.

Maybe I get the conversion screen because of DKCamera and DKPhotoGallery that are still Swift 4.2?

**Comment by zhangao0086** [comment] 2019-10-14 07:10
Closing this thread...

**Closed by zhangao0086** 2019-10-14 07:10 UTC
