### ISSUE TITLE
Custom Camera causes app to crash

### ISSUE THREAD

**Issue by Sun3** [zhangao0086/DKImagePickerController#187] opened 2016-08-31 01:50 UTC
I am using the Custom Camera Delegate but once you take a photo (rotated Landscape then Portrait) and just before we tap Use Photo the app always crashes with below error. I tried this in the Demo app with same results on an iPhone 6 Plus

Error before app crashes

```
Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.

Received memory warning.
```

Any thoughts or suggestions? This does not happen if we do not use the Custom Camera Delegate but I really would like to use the Default iPhone Camera interface.

Thank you

**Comment by zhangao0086** [comment] 2016-09-19 09:41
I can't reproduce it :(

**Comment by zhangao0086** [comment] 2017-08-24 10:27
Closing this thread. Feel free to re-open if your issue is not solved.

**Closed by zhangao0086** 2017-08-24 10:27 UTC
