### ISSUE TITLE
Localization do not work

### ISSUE THREAD

**Issue by chilimovpasha** [zhangao0086/DKImagePickerController#600] opened 2019-06-03 07:49 UTC
Hello!
First of all thanks for your work, its really helpful.

I ran into a problem - even if I change the system language and close the application, the language in the window does not change.

![Simulator Screen Shot - iPhone X - 2019-06-03 at 10 41 55](https://user-images.githubusercontent.com/9354461/58784595-78626080-85ec-11e9-8cb0-0a700fd4d76b.png)
![Simulator Screen Shot - iPhone X - 2019-06-03 at 10 43 10](https://user-images.githubusercontent.com/9354461/58784597-78626080-85ec-11e9-8c0c-1a7418b95448.png)

I chose Russian in the settings but the language in the window is still English. Also I tried to use customLocalizationBlock to rename titles, but can not rename "Camera Roll" and "Cancel".

P.S. Use Cocoapods 1.7.0, supported from iOS 9.0, Xcode 10.2.1.

Can you help me?

**Comment by zhangao0086** [comment] 2019-06-04 11:34
Hi @chilimovpasha The cancel button is created with `UIBarButtonItem(barButtonSystemItem: .cancel, ...`. I can't find the cause of this problem. Could you make an example project that can reproduce it?

**Comment by chilimovpasha** [comment] 2019-06-04 19:20
> Hi @chilimovpasha The cancel button is created with `UIBarButtonItem(barButtonSystemItem: .cancel, ...`. I can't find the cause of this problem. Could you make an example project that can reproduce it?

Hi, I could not but I can describe)
I create DKImagePickerController instance with following:
`maxSelectableCount = 10
assetType = .allPhotos
sourceType = .both
showsEmptyAlbums = false
showsCancelButton = true`

after that use imagePickerController.select(assets: someValues) and the block imagePickerController.didSelectAssets to get assets.
That all.

**Comment by zhangao0086** [comment] 2019-06-06 16:03
Hi @chilimovpasha Could you check the localization settings in the Project Info? I think Russia will not be here, right?
![image](https://user-images.githubusercontent.com/7742344/59047716-f35e9c00-88b6-11e9-8ba8-9c2a4ea58e83.png)

**Comment by chilimovpasha** [comment] 2019-06-07 09:17
Hi @zhangao0086 No, Its there...

**Comment by ajaysaini58** [comment] 2019-06-17 18:15
14 days before the SdWebImage library released an update due to which most features of DkImagePickerController has stopped working(including localisation).

**Comment by zhangao0086** [comment] 2019-06-18 08:02
Hi @ajaysaini58 Sorry for that :(
Could you check the latest develop branch? I've updated it today :)
```
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'develop'
```

**Comment by ajaysaini58** [comment] 2019-06-18 09:51
Hi,
yes. I will check the latest develop branch and will let you whether the
issues have been resolved or not. Thank you for such a swift response.

Regards,
Ajay Kumar Saini

**Comment by ajaysaini58** [comment] 2019-06-18 14:26
Things are working fine. Thanks @zhangao0086 for all your efforts.

**Comment by zhangao0086** [comment] 2019-10-14 07:56
Closing this thread.

**Closed by zhangao0086** 2019-10-14 07:56 UTC

**Comment by Pal-illuminz** [comment] 2021-12-27 07:03
Localization is not working

![Screenshot 2021-12-27 at 12 20 20 PM](https://user-images.githubusercontent.com/75825421/147443264-1a3a4a5a-0598-464c-8cdc-c571a2f18737.png)

![Simulator Screen Shot - iPhone 12 Pro - 2021-12-27 at 12 31 46](https://user-images.githubusercontent.com/75825421/147444334-715ed517-1e6f-47c5-a1e1-87e4d43801dd.png)
