### ISSUE TITLE
DKAssetGroupDetailVC  crashed

### ISSUE THREAD

**Issue by fahied** [zhangao0086/DKImagePickerController#316] opened 2017-05-24 08:12 UTC
Guys, I am having this weird crash on iOS (8,9,10), any ideas to resolve it?

`Crashed: com.apple.main-thread
0  MYAPP                         0x29f364 specialized DKAssetGroupDetailVC.collectionView(UICollectionView, didDeselectItemAt : IndexPath) -> () (DKAssetGroupDetailVC.swift:293)
1  libswiftCore.dylib             0x128856f swift_bridgeObjectRetain + 20
2  MYAPP                         0x294dfc @objc DKAssetGroupDetailVC.collectionView(UICollectionView, didSelectItemAt : IndexPath) -> () + 2858492
3  MYAPP                         0x294dac @objc DKAssetGroupDetailVC.collectionView(UICollectionView, didDeselectItemAt : IndexPath) -> () + 2858412
4  UIKit                          0x2a22794d -[UICollectionView _deselectItemAtIndexPath:animated:notifyDelegate:] + 308
5  UIKit                          0x29c63d47 -[UICollectionView _userSelectItemAtIndexPath:] + 242
6  UIKit                          0x29c63987 -[UICollectionView touchesEnded:withEvent:] + 518
7  UIKit                          0x29bd43fd forwardTouchMethod + 292
8  UIKit                          0x29c21e73 -[UIResponder touchesEnded:withEvent:] + 34
9  UIKit                          0x29bd43fd forwardTouchMethod + 292
10 UIKit                          0x29c21e73 -[UIResponder touchesEnded:withEvent:] + 34
11 UIKit                          0x29bd43fd forwardTouchMethod + 292
12 UIKit                          0x29c21e73 -[UIResponder touchesEnded:withEvent:] + 34
13 UIKit                          0x29a23f25 _UIGestureRecognizerUpdate + 10852
14 UIKit                          0x29a62ec9 -[UIWindow _sendGesturesForEvent:] + 904
15 UIKit                          0x29a6267b -[UIWindow sendEvent:] + 622
16 UIKit                          0x29a33125 -[UIApplication sendEvent:] + 204
17 UIKit                          0x29a316d3 _UIApplicationHandleEventQueue + 5010
18 CoreFoundation                 0x25479dff __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 14
19 CoreFoundation                 0x254799ed __CFRunLoopDoSources0 + 452
20 CoreFoundation                 0x25477d5b __CFRunLoopRun + 794
21 CoreFoundation                 0x253c7229 CFRunLoopRunSpecific + 520
22 CoreFoundation                 0x253c7015 CFRunLoopRunInMode + 108
23 GraphicsServices               0x269b7ac9 GSEventRunModal + 160
24 UIKit                          0x29a9b189 UIApplicationMain + 144
25 MYAPP                         0xec87d main (main.m:21)
26 libdispatch.dylib              0x2506f873 (Missing)`

**Comment by zhangao0086** [comment] 2017-05-24 09:42
I can't reproduce this issue 😢 Could you provide some more information?

**Comment by zhangao0086** [comment] 2017-08-24 10:40
Closing this thread. Feel free to re-open if your issue is not solved.

**Closed by zhangao0086** 2017-08-24 10:40 UTC
