### ISSUE TITLE
Sometimes photos don't appear

### ISSUE THREAD

**Issue by alexanderkhitev** [zhangao0086/DKImagePickerController#461] opened 2018-04-25 11:41 UTC
Hello! Some of our users have experienced the problem that when they see `DKImagePickerController`, but it does not display photos and videos, although users have photos and videos. We use the following settings

```
   let pickerController = DKImagePickerController()
        pickerController.sourceType = .both
        pickerController.singleSelect = true
        pickerController.assetType = .allAssets
```

thanks

**Comment by zhangao0086** [comment] 2018-04-25 12:50
Hi @alexanderkhitev I cannot reproduce it... could you provide me the details?

**Comment by alexanderkhitev** [comment] 2018-04-25 12:58
![1](https://user-images.githubusercontent.com/12511909/39247239-e75962da-48a9-11e8-8cea-107fd46d6b61.png)

**Comment by alexanderkhitev** [comment] 2018-04-25 13:00
Hi @zhangao0086 
Unfortunately, I can not give more technical details, since this is an ordinary user (not a tester) and he sent us this screenshot. This user has an iPhone X, and he also allowed the application to access the Photo App.

**Comment by alexanderkhitev** [comment] 2018-04-25 13:06
@zhangao0086  I tried to disable and enable access to photos and then show `DKImagePickerController`, but I could not reproduce the bug. My colleagues also tried to reproduce the bug but also were not successful. we assumed that the error is about the same as in # 150 issue, but no, there the developer had the exact number of photos in the albums and some images, in our case, the user has 0 images in all albums. Only three users have encountered this problem.

**Comment by zhangao0086** [comment] 2018-04-25 14:12
All of the three users are using iPhone X?

**Comment by zhangao0086** [comment] 2018-04-25 15:13
I appreciate your taking time to trying to reproduce this issue! I'll do more tests on iPhoneX!

**Comment by alexanderkhitev** [comment] 2018-04-25 15:13
Thank you so much!

**Comment by gaidukov-nikita** [comment] 2018-04-27 18:42
Hi @zhangao0086. The weirdest thing is that user said that when he copied images to our app's album  (we create an album and export images there) he was able to see and select them from app's album, but Camera Roll was still empty. Not sure if this is helpful. Let us know if you need any other information.

**Comment by gaidukov-nikita** [comment] 2018-04-29 09:27
@zhangao0086 no, we do not. This is our set up:
```
        let pickerController = DKImagePickerController()
        pickerController.sourceType = .both
        pickerController.singleSelect = true
        pickerController.assetType = .allAssets
        pickerController.didSelectAssets = { (assets: [DKAsset]) in
        .......
        }

```

Should we initialize our picker controller with a `DKImageGroupDataManager` instance as a parameter?

**Comment by alexanderkhitev** [comment] 2018-04-30 14:56
@zhangao0086  I did init      `let groupDataManagerConfiguration = DKImageGroupDataManagerConfiguration()` but I got error **Use of unresolved identifier**

**Comment by zhangao0086** [comment] 2019-03-08 12:27
Closing this thread... Feel free to reopen it if the issue persists.

**Closed by zhangao0086** 2019-03-08 12:27 UTC
