### ISSUE TITLE
4.0.0-Beta: FLAnimatedImage reference causes compile error

### ISSUE THREAD

**Issue by esbenr** [zhangao0086/DKImagePickerController#424] opened 2018-01-10 08:49 UTC
DKImagePicker ver. 4.0.0-Beta uses FLAnimatedImage as dependency (installed with CocoaPod).
The integration/usage causes build error:

/.../Pods/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:9: Include of non-modular header inside framework module 'SDWebImage.FLAnimatedImageView_WebCache': '/.../Pods/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h'

"Could not build Objective-C module 'SDWebImage'"

See screenshot.
![skaermbillede 2018-01-10 kl 09 45 53](https://user-images.githubusercontent.com/560120/34763443-7f71862c-f5eb-11e7-8a64-06966d29e1d8.png)

**Comment by zhangao0086** [comment] 2018-01-10 10:49
Hi @esbenr Thanks for your feedback!

Have you tried clearing the build cache?

> Go into Developer/Xcode/DerivedData and delete the folder for your framework. (Or just delete DerivedData itself)
> 
> If you have a build of you app in a running simulator you'll need to delete the app there.
> 
> Then Clean & Build

**Comment by pak-amsiq** [comment] 2018-01-25 15:51
+1.

@zhangao0086 - I already tried cleaning

**Comment by zhangao0086** [comment] 2018-01-26 00:14
@pak-amsiq What version of CocoaPods are you using? Could you upload a project that reproduces the problem?

**Comment by pak-amsiq** [comment] 2018-01-26 07:40
I'm using cocoapods 1.4.0.

I've try to generate a test project containing the issue.

**Comment by pak-amsiq** [comment] 2018-01-26 10:39
I'm not able to reproduce the errors in my example project. 

But I can provide some additional information from the build issue: 

Error 1: 
/Users/pak/Library/Developer/Xcode/DerivedData/XXX-hbbgqalpyrajntgtwdxdymapyhjw/Build/Products/Release-iphoneos/XXX.app/Frameworks/SDWebImage.framework: No such file or directory

Error 2: 
/Users/pak/Library/Developer/Xcode/DerivedData/XXX-hbbgqalpyrajntgtwdxdymapyhjw/Build/Products/Release-iphoneos/XXX.app/Frameworks/SDWebImage.framework: No such file or directory
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

**Comment by pak-amsiq** [comment] 2018-01-29 07:30
@zhangao0086  Any ideas?

**Comment by pak-amsiq** [comment] 2018-02-01 15:28
@zhangao0086 Any updates?

**Comment by zhangao0086** [comment] 2018-02-02 00:33
@pak-amsiq Sorry for the later response.

Have you seen this thread? https://stackoverflow.com/a/28552525/907422

**Comment by pak-amsiq** [comment] 2018-02-04 19:07
@zhangao0086 Thanks for your input. 

Setting "Allow Non-modular Includes in Framework Modules" to TRUE fixed this issue.

**Comment by zhangao0086** [comment] 2018-02-05 07:51
Closing this thread :) Feel free to re-open if it does not solve your problem :)

**Comment by pak-amsiq** [comment] 2018-02-28 20:32
@zhangao0086, this issue still appearing. 

I was using the old version 3.*, when my build succeeded. 

Any other suggestions to fix this issue? 

Please reopen this issue.

**Comment by zhangao0086** [comment] 2018-03-01 02:49
@pak-amsiq Could you post me a small project that can reproduce this issue?

**Comment by pak-amsiq** [comment] 2018-03-12 19:56
As mentioned, I wasn't able to reproduce this issue in a example project. 

My project includes extensions which uses 'SDWebImage' lib directly, which could interfere with your lib which includes 'SDWebImage'... 

I found a solution where I only use main functionality from your lib:

pod 'DKImagePickerController', '4.0.0-beta', :subspecs => ['Core', 'ImageDataManager', 'Resource']

My extensions still includes 'SDWebImage', and doesn't seem to interfere with your library now. 

This linking issue could occur due to multiple usages of 'SDWebImage'.

You could close this issue for now, as its not a issue with this solution. 

Thank you for your time.

**Comment by pak-amsiq** [comment] 2018-03-21 18:42
@zhangao0086

**Comment by zhangao0086** [comment] 2018-03-22 05:31
@pak-amsiq Thank you very much for your detailed analysis of this issue! I'll look for ways to replace SDWebImage in the future release 😃

**Comment by ajithkumar666** [comment] 2018-12-31 05:34
@zhangao0086 i am getting following errors **when archiving**. but no issues when run on iphone or simulator.so i can not archiving. 

1. Could not build Objective-C module 'DKImagePickerController'.
2. Cannot find interface declaration for 'FLAnimatedImageView', superclass of 'DKPhotoImageView'.
3. Could not build module 'DKPhotoGallery'

**Comment by zhangao0086** [comment] 2020-06-09 14:42
Replaced FLAnimatedImageView with SwiftyGif.

**Closed by zhangao0086** 2020-06-09 14:42 UTC
